# Generated by Django 2.2.6 on 2019-10-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='author',
        ),
        migrations.RemoveField(
            model_name='code',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='code',
            name='status',
        ),
        migrations.RemoveField(
            model_name='code',
            name='updated_on',
        ),
    ]
